commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ce-1.9.2.0 
        version: 1.9.2.0 
        source:
          url: https://github.com/OpenMage/magento-mirror.git
          type: git
          reference: 1.9.2.1
      - name: magento-ce-1.9.2.1 
        version: 1.9.2.1 
        source:
          url: https://github.com/OpenMage/magento-mirror.git
          type: git
          reference: 1.9.2.1
